---
development:
  dialect: mysql
  database: testdb
  user: root
  password: root
  host: mariadb
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "jdbc:mariadb://mariadb:3306/testdb"}}

production:
  url: {{envOr "DATABASE_URL" "jdbc:mariadb://mariadb:3306/testdb"}}
